### ISSUE TITLE
How to invalidate an instance method only for one instance

### ISSUE THREAD

**Issue by madEng84** [infoscout/django-cache-utils#10]
Hi, this is not an issue but a request for a more detailed documentation

I have this model (the one of the docs)
```
class City(models.Model):
    # ... field declarations

    objects = CityManager()

    # an example how to cache django model methods by instance id
    def has_offers(self):
        @cached(30, 'offers')
        def offer_count(pk):
            return self.offer_set.count()
        return offer_count(self.pk) > 0

```
how can i invalidate cache only for the City instance with pk = 1?

Thank you
Regards

**Comment by madEng84** [comment]
@RevolutionTech can you help me on this?
Thanks

**Comment by RevolutionTech** [comment]
Hi @madEng84,

I'm afraid I've just recently adopted this repo, so please bare with me as I am still not incredibly familiar with the code.

However, I _think_ you can invalidate the cache on `pk=1` in this case with:

```python
offer_count.invalidate(1)
```

**Comment by madEng84** [comment]
Hi @RevolutionTech 
Is not possible to do `offer_count.invalidate(1)` because `offer_count` is a nested method in the instance method `has_offers`

I resolved in this manner (not so beauty but perfect for my purpose, because i don't want to invalidate group but instance method)

```
from django.core.cache import cache
from cache_utils.decorators import cached


class City(models.Model):
    # ... field declarations

    # an example how to cache django model methods by instance id
    def has_offers(self):
        @cached(60*60*24*30, 'offers_{0}'.format(self.pk)) #30 days
        def offer_count(pk):
            return self.offer_set.count()
        return offer_count(self.pk) > 0

    @classmethod
    def invalidate_offer_count(cls, pk)
        cache.invalidate_group('offers_{0}'.format(pk))
```

Hope it helps and i think this code could be inserted in the README to help other users

**Comment by RevolutionTech** [comment]
Ah, I see. Yeah, it would be challenging to factor `offer_count` out as a method of the class. Thanks for sharing, @madEng84.
