### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by PetrDlouhy** [infoscout/django-cache-utils#11]
The PyPI package (https://pypi.python.org/pypi/django-cache-utils) seems to be quite old. Please update it to current version.

**Comment by RevolutionTech** [comment]
Hi @PetrDlouhy, please see https://github.com/infoscout/django-cache-utils/issues/3.

Unfortunately we are not the owners of that PyPi package, and it has since been abandoned by the owner. I've reached out to the original owner to see if he is willing to transfer ownership, but unfortunately I have not received any response to those requests.

**Comment by PetrDlouhy** [comment]
@kmike Could you update the PyPI package or give us access rights please?

**Comment by tylerecouture** [comment]
Any chance you could post this on PyPi as a new package, discontinuing form the abandoned one?

**Comment by RevolutionTech** [comment]
We are considering doing that, but also still actively trying to get access to the `django-cache-utils` project on PyPi.

**Comment by PetrDlouhy** [comment]
@RevolutionTech Any news on this? It is a long time, so I would consider making new PyPI package such as `django-cache-util`. If @kmike will be contacted in the future, the original package can still be updated.

**Comment by RevolutionTech** [comment]
I appreciate your patience on this. I've been meaning to do some general cleanup before releasing the package on PyPi under a new name but haven't gotten around to it yet. I added it my sprint this week, so I'll aim to get it released this week or next.

**Comment by RevolutionTech** [comment]
Thanks for your patience. We have now released the package as `djcacheutils`.
```shell
$ pip install djcacheutils
```

**Comment by PetrDlouhy** [comment]
Nice :-)
