### ISSUE TITLE
Support for Python3?

### ISSUE THREAD

**Issue by tylerecouture** [infoscout/django-cache-utils#12]
Does this suppor Python3?

I'm getting this error:
`ImportError: cannot import name 'smart_unicode'`

I installed via pip, and it shows this:
django-cache-utils==0.7.2

**Comment by RevolutionTech** [comment]
Our latest version 1.1.3 supports Python 3, but unfortunately we are not on PyPi (this repo was forked [from Bitbucket](https://bitbucket.org/kmike/django-cache-utils)). If you want to install 1.1.3, you will have to install from the git repo directly.

```
$ pip install git+https://github.com/infoscout/django-cache-utils.git@1.1.3
```

**Comment by tylerecouture** [comment]
I'm still getting the same error:
`ImportError: cannot import name 'smart_unicode'`

Despite having 1.1.3?
```
$ pip freeze
...
django-cache-utils==1.1.3
```

**Comment by RevolutionTech** [comment]
Sorry, my bad. Python 3 support wasn't actually added until 2.0.0. Please try installing 2.0.0 and let me know if you run into issues after that.

**Comment by tylerecouture** [comment]
Works!

**Comment by RevolutionTech** [comment]
Awesome! Sorry about the mixup on my end.
